spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:defaultDB;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username:
    password:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 50
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/h2/autotrading;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
---
spring:
  config:
    activate:
      on-profile: integration-embedded-test,integration-test
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false

---
spring:
  config:
    activate:
      on-profile: develop,prod
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:file:/app/data;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false