version: '3'
services:
  mysql:
    container_name: integration-test-mysql
    platform: linux/amd64
    image: mysql:5.7.42
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  localstack:
    container_name: integration-test-localstack
    image: localstack/localstack:0.12.6
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

