name: format

on:
  push:
    branches: [ feature/*, hotfix/* ]
  #pull_request:
  #  branches: [ master ]

jobs:
  formatting:
    name: code formatting
    runs-on: ubuntu-latest

    steps:
      ## https://github.com/axel-op/googlejavaformat-action
      ## https://github.com/google/google-java-format
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace --skip-reflowing-long-strings --skip-javadoc-formatting"